Fixes to .travis.yml.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -95,13 +95,12 @@ install:
   case "$BUILD" in
     stack)
       ulimit -n 4096
-      stack --no-terminal --install-ghc $ARGS test --only-dependencies --fast --flag "pandoc-citeproc:test_citeproc" --flag "aeson:fast"
+      stack --no-terminal --install-ghc $ARGS test --only-dependencies --fast --flag "pandoc-citeproc:test_citeproc" --flag "pandoc-citeproc:embed_data_files" --flag "aeson:fast"
       ;;
     cabal)
       cabal --version
       travis_retry cabal update
-      cabal install hsb2hs
-      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --disable-optimization -ffast --reorder-goals --max-backjumps=-1 $CABALARGS
+      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --disable-optimization -ffast -fembed_data_files -ftest_citeproc --reorder-goals --max-backjumps=-1 $CABALARGS
       ;;
   esac
 
@@ -110,19 +109,16 @@ script:
   case "$BUILD" in
     stack)
       ulimit -n 4096
-      stack --no-terminal $ARGS test --haddock --no-haddock-deps --flag "pandoc-citeproc:test_citeproc" --flag "aeson:fast" --ghc-options="-O0 -Wall -fno-warn-unused-do-bind -Werror"
-      EC=$?
-      stack exec test-citeproc || echo "expected to fail..."
+      stack --no-terminal $ARGS test --haddock --no-haddock-deps --flag "pandoc-citeproc:test_citeproc" --flag "pandoc-citeproc:embed_data_files" --flag "aeson:fast" --fast --ghc-options="-O0 -Wall -fno-warn-unused-do-bind -Werror" && \
+      EC=$? && \
+      stack exec test-citeproc || echo "expected to fail..." && \
       exit $EC
       ;;
     cabal)
-      cabal configure --enable-tests --enable-benchmarks -ffast -v2 --ghc-options="-O0 -Wall -fno-warn-unused-do-bind -Werror"
-      cabal build
-      cabal check
+      cabal sdist --output-directory=sourcedist && \
+      cd sourcedist && \
+      cabal configure --enable-tests --enable-benchmarks -ffast -ftest_citeproc -fembed_data_files -v2 --ghc-options="-O0 -Wall -fno-warn-unused-do-bind -Werror" --disable-optimizations && \
+      cabal build && \
       cabal test
-      cabal copy
-      cabal sdist
-      SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
-        (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
       ;;
   esac
